"""StakeholderMessage schema — output of the Operator Agent for targeted notifications."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class StakeholderMessage(BaseModel):
    """
    A tailored message for a specific stakeholder audience.
    Generated by the Operator Agent. Delivered via FCM push, dashboard, or TTS loudspeaker.
    """
    id: str = ""
    audience: Literal[
        "public", "rescue_1122", "hospital", "lesco", "wasa",
        "traffic_police_transport_authority", "media_command_center",
        "mosque", "cm_health_program"
    ]
    channel: Literal["push", "sms", "email", "dashboard", "loudspeaker_tts"]
    language: Literal["urdu", "roman_urdu", "english"]
    content: str
    urgency: Literal["info", "advisory", "urgent", "emergency"] = "info"
    crisis_id: str = ""

    # For mosque announcements: multi-format output
    roman_urdu_transliteration: str | None = None
    english_translation: str | None = None

    # TTS audio URL (populated after Google Cloud TTS generates audio)
    tts_audio_url: str | None = None
